baseURL = 'https://yusukebe.github.io/slides'
languageCode = 'ja-up'
title = 'yusukebe/slides'

theme = "reveal-hugo"

[markup]
  [markup.highlight]
    style = 'monokai'

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "stylesheets/custom-theme.scss"
custom_theme_compile = true
