baseURL = 'https://yusukebe.github.io/slides'
languageCode = 'ja-up'
title = 'yusukebe/slides'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true